name: "Chemistry"
description: "A site to use for my AP Chemistry notes."
chapters: [1]

email: "bionicle.dragon@gmail.com"
github: "porglezomp"
twitter: "stickfigure42"
repo: "porglezomp.github.io/porglezomp/ap-chem"

url: "//porglezomp.github.io/ap-calc"

markdown: redcarpet
permalink: pretty
highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
